#!/bin/sh
#
# chiisu: screenshot with style
# usage:
#    -tl    display dzen on top-left 
#    -tr    display dzen on top-right 
#    -bl    display dzen on bottom-left 
#    -br    display dzen on bottom-right 
#    -n     display notification using notify-osd insteads
#

FN="DejaVu:bold:size=9"
W=300
H=60
X=100
Y=70

take() {
    printf -v date "%(%F)T"
    printf -v time "%(%I-%M-%S)T"
    savedir="${HOME}/Pictures/Screenshots-chiisu/${date}"
    mkdir -p ${savedir}

    if [ "$SERVER" == "gnome" ]; then
        gnome-screenshot -f "${savedir}/chiisu-${date}-${time}".png > /dev/null 2>&1
        sleep 0.5s
    else
        sleep 0.5s
        import -window root "${savedir}/chiisu-${date}-${time}".png
    fi
}


case $1 in
    -n)
        NOTIFY="true"
    ;;
    -tl)
    ;;
    -tr)
        X=$((1920 - W - X))
    ;;
    -bl)
        Y=$((1080 - H - Y))
    ;;
    -br|*)
        X=$((1920 - W - X))
        Y=$((1080 - H - Y))
    ;;
esac

if [[ -n $NOTIFY ]]; then
    notify-send "Chiisu! Taking screenshot ..."
    take
    exit
fi
{
    echo -e "      ^fn(Wuncon Siji:size=10)\ue1da^fn() Chiisu! Taking screenshot ..."; take 
} | dzen2 -ta l -bg $(xrgc bg) -fg $(xrgc fg) -fn "${FN}"  -x ${X} -y ${Y} -w ${W} -h ${H}

