#!/bin/sh

current_workspace=$(xdotool get_desktop)
group_total=4

switch_workspace(){
	for (( i = 1; i <= $((group_total+1)); i++ )); do
		waitron group_deactivate $((1+$i))
	done
	waitron group_activate $((1+$1))
}

send_window(){
	if [[ "$current_workspace" != $1 ]]; then
		waitron group_add_window $((1+$1))
		switch_workspace $1
	fi
}

put_window(){
	if [[ "$current_workspace" -lt 1 ]]; then
		waitron group_add_window $((1+$1))
		switch_workspace $1
	fi
}

case $1 in
	switch_workspace)
		switch_workspace $2
	;;
	send_window)
		send_window $2
	;;
	put_window)
		put_window 1
	;;
esac
