#!/bin/sh
RESOURCES="$HOME/.cache/wal/colors.Xresources"
gc(){
case $1 in 
    fg)
        cat $RESOURCES | egrep -m1 "*\.?foreground:" | awk '{print $NF}' 
    ;;
    bg)
        cat $RESOURCES | egrep -m1 "*\.?background:" | awk '{print $NF}' 
    ;;
    *) 
        cat $RESOURCES | egrep -m1 "^\*\.?color$1:" | awk '{print $NF}'
    ;;
esac
}

writ(){
cat <<EOF
@define-color bg $(gc bg);
@define-color bg_darken $(gc bg);
@define-color clear rgba(0, 0, 0, 0);
@define-color bg_alt $(gc 1);
@define-color fg $(gc fg);
EOF
}

sleep 1
wallpath=$(cat ~/.fehbg | awk -F\' '{print $6}' | grep .)
sudo cp "$HOME/${wallpath}" /etc/lightdm/bg.jpg
writ > /tmp/colors.css
sudo mv /tmp/colors.css /usr/share/themes/Yuune-lightdm/gtk-3.0/colors.css
