#!/bin/sh
#
#      ▘   ▌       ▌   ▐▘
#   ▌▌▌▌▛▌▛▌▛▌▌▌▌▛▘▛▌█▌▜▘▛▘▛▘
# ▗ ▙▙▌▌▌▌▙▌▙▌▙▙▌▙▖▌▌▙▖▐ ▌ ▙▖

#
# Cooking the window since 2016
# And you still not noticing me senpai...
#
# @type config
# @return void
# @param none
#
PRESET="noir-thin"
BAR_PRESET="noir"

export WM=windowchef

# ensure that wminitrc is not sourced again by checking sxhkd
[ -z `pidof sxhkd` ] && source ~/.wminitrc

# apply wallpaper
source ~/.fehbg

# check instance
[ ! -z `pidof sxhkd` ] && pkill sxhkd
[ ! -z `pidof ruler` ] && pkill ruler
[ ! -z `pidof compton` ] && pkill compton
[ ! -z `pidof lemonbar` ] && pkill lemonbar
[ ! -z `pidof dunst` ] && pkill dunst
[ ! -z `pidof conky` ] && pkill conky

sleep 0.1s

# keybindings
sxhkd &

# jeanne d'arc of window
ruler &

# compositor
compton &

# notification daemon
dunst-xrdb &

# panel
$XDG_CONFIG_HOME/lemonbar/${BAR_PRESET} &

# retrieve preset
source $XDG_CONFIG_HOME/windowchef/preset/${PRESET}

# apply
waitron wm_config enable_borders true
waitron wm_config border_width $border
waitron wm_config color_focused 0x$focused
waitron wm_config color_unfocused 0x$unfocused
waitron wm_config internal_border_width $internal_border
waitron wm_config internal_color_focused 0x$internal_focused
waitron wm_config internal_color_unfocused 0x$internal_unfocused
waitron wm_config gap_width all $gaps
waitron wm_config gap_width top $gaps_top
waitron wm_config grid_gap_width $gaps_grid
waitron wm_config groups_nr $group_total
waitron wm_config sticky_windows true
waitron wm_config cursor_position middle
waitron wm_config enable_resize_hints true
waitron wm_config enable_last_window_focusing true
waitron wm_config enable_sloppy_focus false
waitron wm_config pointer_actions move resize_side resize_corner
waitron wm_config pointer_modifier super
waitron wm_config click_to_focus any
waitron wm_config apply_settings true
